import 'package:jaspr/server.dart';
import 'package:jaspr_content/jaspr_content.dart' hide FilesystemLoader;
import 'package:jaspr_content/theme.dart';
import 'package:jaspr_router/jaspr_router.dart';
import 'package:mraleph/grammars.dart';

import 'extensions/sidenote_extension.dart';
import 'forked/jaspr/filesystem_loader.dart';
import 'forked/jaspr/code_block.dart';
import 'layouts/front_page.dart';
import 'layouts/blogpost.dart';
import 'outputs/atom_output.dart';

import 'main.server.options.dart';

void main() {
  Jaspr.initializeApp(options: defaultServerOptions);

  runApp(
    ContentApp.custom(
      loaders: [FilesystemLoader('content', keepSuffixPattern: RegExp(r'.*\.(md|html)$'))],
      configResolver: PageConfig.all(
        dataLoaders: [FilesystemDataLoader('content/_data')],
        parsers: [MarkdownParser()],
        layouts: [
          FrontPageLayout(),
          BlogpostLayout(),
        ],
        theme: const ContentTheme.none(),
        components: [
          ListOfPosts.component,
          ListOfTalks.component,
          CodeBlock(grammars: allGrammars),
        ],
        extensions: [SidenoteExtension()],
        secondaryOutputs: [AtomOutput()],
      ),
      eagerlyLoadAllPages: true,
      routerBuilder: (List<List<RouteBase>> routes) {
        return Router(
          routes: [
            // Spread the routes generated by jaspr_content
            ...routes.expand((r) => r),
          ],
        );
      },
    ),
  );
}
